version: "3"

services:

  spotify-webapp:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - secrets/secrets.yml.dec
    environment:
      - LOCAL=True
      - GUNICORN_reload=True
    depends_on:
      - redis

  redis:
    build: ./redis
    ports:
      - 6379