version: "3"

services:

  spotify-app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - secrets/secrets.yml.dec
    environment:
      - LOCAL=True
      - GUNICORN_RELOAD=True
      - PUBLIC_URL="http://localhost:8080/"
    depends_on:
      - redis

  redis:
    build: ./redis
    ports:
      - 6379